bosses:
  # Example boss configuration using message references
  Example:
    victory_message_id: DEFAULT_VICTORY # Message ID for the boss victory message
    top_players_to_show: 3 # How many players will be shown in the top damage list
    position_format_id: DEFAULT # Format ID for the position in the top damage list
    broadcast_message: true # Whether to broadcast the victory message
    personal_message_id: DEFAULT # Message ID for the personal damage message
    non_participant_message_id: DEFAULT # Message ID for the non-participant damage message
    hologram_type: FANCY # Can be NONE, FANCY 

  # Example boss with epic formatting
  EPIC_BOSS:
    victory_message_id: BOSS_EPIC_VICTORY
    top_players_to_show: 5
    position_format_id: EPIC_BOSS
    broadcast_message: true
    personal_message_id: EPIC
    non_participant_message_id: EPIC

  # Example raid boss
  RAID_BOSS:
    victory_message_id: RAID_BOSS_VICTORY
    top_players_to_show: 3
    position_format_id: DEFAULT
    broadcast_message: true
    personal_message_id: DEFAULT
    non_participant_message_id: DEFAULT

    # Example no custom message boss
    No_Custom_Message: []

# Default configuration for bosses
default_boss_config:
  victory_message_id: DEFAULT_VICTORY
  top_players_to_show: 3
  position_format_id: DEFAULT
  broadcast_message: true
  personal_message_id: DEFAULT
  non_participant_message_id: DEFAULT

# Format for displaying damage values
damage_format: "%.2f"
percentage_format: "%.1f"
