name: DamageTracker_For_MythicMobs
version: '${project.version}'
main: com.elplatano0871.damagetracker.DamageTracker
api-version: '1.19'
depend: [MythicMobs, PlaceholderAPI]

commands:
  damagetracker:
    description: Main command for DamageTracker plugin
    usage: /<command> [reload|damage|top]
    permission: damagetracker.use

permissions:
  damagetracker.use:
    description: Allows using the DamageTracker command
    default: true
  damagetracker.reload:
    description: Allows reloading the DamageTracker plugin
    default: op